"use client";

import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import type { ReactNode } from "react";

import { Card, CardAction, CardContent } from "@/components/shadcn/card/card";
import { Progress } from "@/components/shadcn/progress";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/shadcn/tooltip";
import { buildComplianceDetailPath } from "@/lib/compliance/compliance-detail-url";
import { getReportTypeForCompliance } from "@/lib/compliance/compliance-report-types";
import { formatComplianceFrameworkTitle } from "@/lib/compliance/framework-title";
import {
  getScoreIndicatorClass,
  type ScoreColorVariant,
} from "@/lib/compliance/score-utils";
import { cn } from "@/lib/utils";
import { ScanEntity } from "@/types/scans";

import { getComplianceIcon } from "../icons";

import { ComplianceDownloadContainer } from "./compliance-download-container";

interface ComplianceCardProps {
  title: string;
  version: string;
  passingRequirements: number;
  totalRequirements: number;
  prevPassingRequirements: number;
  prevTotalRequirements: number;
  scanId: string;
  complianceId: string;
  id: string;
  selectedScan?: ScanEntity;
  /**
   * True when this compliance_id is the highest CIS version for its provider.
   * Only the latest CIS variant per provider has a PDF generated by the
   * backend, so older variants must not expose the PDF download button.
   * Ignored for non-CIS frameworks.
   */
  isLatestCisForProvider?: boolean;
  /**
   * Watchlist control rendered in the card's top-right corner, beside the
   * export action, so it costs no vertical room. Cloud-only and gated on
   * MANAGE_SCANS, so it is absent (rather than disabled) whenever the
   * viewer cannot curate the organization's watchlist.
   */
  watchlistAction?: ReactNode;
}

export const ComplianceCard: React.FC<ComplianceCardProps> = ({
  title,
  version,
  passingRequirements,
  totalRequirements,
  scanId,
  complianceId,
  id,
  isLatestCisForProvider = false,
  watchlistAction,
}) => {
  const searchParams = useSearchParams();
  const router = useRouter();
  const hasRegionFilter = searchParams.has("filter[region__in]");

  const formattedTitle = formatComplianceFrameworkTitle(title, version);

  const ratingPercentage = Math.floor(
    (passingRequirements / totalRequirements) * 100,
  );

  const getRatingVariant = (value: number): ScoreColorVariant => {
    if (value <= 10) return "danger";
    if (value <= 40) return "warning";
    return "success";
  };

  const navigateToDetail = () => {
    router.push(
      buildComplianceDetailPath({
        title,
        complianceId: id,
        version,
        scanId,
        regionFilter: searchParams.get("filter[region__in]"),
      }),
    );
  };

  return (
    <Card variant="base" padding="none" interactive className="relative">
      <button
        type="button"
        aria-label={`Open ${formattedTitle} compliance details`}
        onClick={navigateToDetail}
        className="focus-visible:ring-border-neutral-secondary/50 w-full rounded-xl bg-transparent px-4 py-3 text-left outline-none focus-visible:ring-2"
      >
        <CardContent>
          <div className="flex w-full flex-col gap-3">
            <div
              className={cn(
                "flex items-center gap-3",
                watchlistAction ? "pr-16" : "pr-9",
              )}
            >
              {getComplianceIcon(title) && (
                <div className="border-border-neutral-tertiary flex h-10 w-10 min-w-10 shrink-0 items-center justify-center rounded-md border bg-slate-50">
                  <Image
                    src={getComplianceIcon(title)}
                    alt={`${title} logo`}
                    width={32}
                    height={32}
                    className="h-8 w-8 object-contain"
                  />
                </div>
              )}
              <div className="flex min-w-0 flex-1 flex-col">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <h4 className="truncate text-sm leading-5 font-bold">
                      {formattedTitle}
                    </h4>
                  </TooltipTrigger>
                  <TooltipContent>{formattedTitle}</TooltipContent>
                </Tooltip>
                <small className="truncate">
                  <span className="mr-1 text-xs font-semibold">
                    {passingRequirements} / {totalRequirements}
                  </span>
                  Passing Requirements
                </small>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex items-center justify-between gap-3 text-xs">
                <span className="text-text-neutral-secondary font-medium tracking-wider">
                  Score:
                </span>
                <span className="text-text-neutral-secondary">
                  {ratingPercentage}%
                </span>
              </div>
              <Progress
                aria-label="Compliance score"
                value={ratingPercentage}
                className="border-border-neutral-secondary h-2.5 border drop-shadow-sm"
                indicatorClassName={getScoreIndicatorClass(
                  getRatingVariant(ratingPercentage),
                )}
              />
            </div>
          </div>
        </CardContent>
      </button>
      <CardAction
        className="absolute top-2 right-2 z-10 flex items-center gap-1"
        role="group"
        aria-label="Compliance actions"
      >
        <ComplianceDownloadContainer
          compact
          orientation="column"
          buttonWidth="icon"
          presentation="dropdown"
          scanId={scanId}
          complianceId={complianceId}
          reportType={getReportTypeForCompliance(
            title,
            complianceId,
            isLatestCisForProvider,
          )}
          disabled={hasRegionFilter}
        />
        {watchlistAction}
      </CardAction>
    </Card>
  );
};
