apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prowler-api.fullname" . }}-config
  labels:
    {{- include "prowler-api.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.mainConfig | nindent 4 }}
