apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowler-api.fullname" . }}
  labels:
    {{- include "prowler-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prowler-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowler-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prowler-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- range $name,$config := .Values.containers }}
      {{- if $config.enabled }}
        - name: {{ $name }}
          securityContext:
            {{- toYaml $config.securityContext | nindent 12 }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "prowler-api.fullname" $ }}
          command:
            {{- toYaml $config.command | nindent 12 }}
          {{- if $config.ports }}
          ports:
            {{- toYaml $config.ports | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml $config.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $config.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "prowler-api.fullname" $ }}-config
              mountPath: {{ $.Values.releaseConfigRoot }}{{ $.Values.releaseConfigPath }}
              subPath: config.yaml
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      volumes:
        - name: {{ include "prowler-api.fullname" . }}-config
          configMap:
            name: {{ include "prowler-api.fullname" . }}-config
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
