rules:
  secrets-outside-env:
    ignore:
      - api-bump-version.yml
      - api-container-build-push.yml
      - api-tests.yml
      - backport.yml
      - docs-bump-version.yml
      - issue-triage.lock.yml
      - mcp-container-build-push.yml
      - pr-merged.yml
      - prepare-release.yml
      - sdk-bump-version.yml
      - sdk-container-build-push.yml
      - sdk-refresh-aws-services-regions.yml
      - sdk-refresh-oci-regions.yml
      - sdk-tests.yml
      - ui-bump-version.yml
      - ui-container-build-push.yml
      - ui-e2e-tests-v2.yml
  superfluous-actions:
    ignore:
      - pr-check-changelog.yml
      - pr-conflict-checker.yml
      - prepare-release.yml
