apiVersion: v1
kind: Secret
metadata:
  name: devsecops-prowler-cronjob-secret
  namespace: defectdojo
type: Opaque
stringData:
  awsId: myAWSSecretID
  awsSecretKey: myAWSSecretKey
  awsS3Bucket: myAWSS3Bucket
