flag_management:
  default_rules:
    carryforward: true

component_management:
  individual_components:
    - component_id: "prowler"
      paths:
        - "prowler/**"
    - component_id: "api"
      paths:
        - "api/**"

comment:
  layout: "header, diff, flags, components"
