# Docker Compose override for CI/CD environments
# This file solves permission issues by running containers with the same UID/GID as the CI runner
version: '3.8'

services:
  api:
    # Run as the same user as the CI runner to avoid permission issues
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-1000}"

  worker:
    # Workers also need the same user mapping
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-1000}"

  worker-beat:
    # Worker-beat also needs the same user mapping
    user: "${DOCKER_USER:-1000}:${DOCKER_GROUP:-1000}"
