### Account, Check and/or Region can be * to apply for all the cases.
### Account == <Okta organization URL, e.g. https://acme.okta.com>
### Resources and tags are lists that can have either Regex or Keywords.
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Accounts, Regions, Resources and/or Tags.
###########################  MUTELIST EXAMPLE  ###########################
Mutelist:
  Accounts:
    "https://acme.okta.com":
      Checks:
        "signon_global_session_idle_timeout_15min":
          Regions:
            - "*"
          Resources:
            - "Default Policy"
