{{- if .Values.django.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prowler.djangoServiceAccountName" . }}
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
  {{- with .Values.django.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prowler.fullname" . }}-generate-django-secrets
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    metadata:
      labels:
        {{- include "prowler.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "prowler.djangoServiceAccountName" . }}
      containers:
        - name: generate-secrets
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              openssl genrsa -out /tmp/private.pem 2048
              DJANGO_TOKEN_SIGNING_KEY=$(cat /tmp/private.pem | base64)
              openssl rsa -in /tmp/private.pem -pubout -out /tmp/public.pem
              DJANGO_TOKEN_VERIFYING_KEY=$(cat /tmp/public.pem | base64)
              DJANGO_SECRETS_ENCRYPTION_KEY=$(openssl rand -base64 32)
              kubectl create secret generic {{ include "prowler.fullname" . }}-django-secrets \
                --from-literal=DJANGO_TOKEN_SIGNING_KEY="$DJANGO_TOKEN_SIGNING_KEY" \
                --from-literal=DJANGO_TOKEN_VERIFYING_KEY="$DJANGO_TOKEN_VERIFYING_KEY" \
                --from-literal=DJANGO_SECRETS_ENCRYPTION_KEY="$DJANGO_SECRETS_ENCRYPTION_KEY"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      restartPolicy: Never
      volumes:
        - name: tmp
          emptyDir: {}
  backoffLimit: 4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prowler.fullname" . }}-django-secrets-role
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prowler.fullname" . }}-django-secrets-rolebinding
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prowler.fullname" . }}-django-secrets-role
subjects:
  - kind: ServiceAccount
    name: {{ include "prowler.djangoServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
