name: 💡 Feature Request
description: Suggest an idea for this project
labels: ["feature-request", "status/needs-triage"]

body:
  - type: checkboxes
    id: search
    attributes:
      label: Feature search
      options:
        - label: I have searched the existing issues and this feature has not been requested yet or is already in our [Public Roadmap](https://roadmap.prowler.com/roadmap)
          required: true
  - type: dropdown
    id: component
    attributes:
      label: Which component would this feature affect?
      multiple: true
      options:
        - Prowler CLI/SDK
        - Prowler API
        - Prowler UI
        - Prowler Dashboard
        - Prowler MCP Server
        - Documentation
        - New component/Integration
    validations:
      required: true
  - type: dropdown
    id: provider
    attributes:
      label: Related to specific cloud provider?
      multiple: true
      options:
        - AWS
        - Azure
        - GCP
        - Kubernetes
        - GitHub
        - Microsoft 365
        - All providers
        - Not provider-specific
  - type: textarea
    id: Problem
    attributes:
      label: New feature motivation
      description: Is your feature request related to a problem? Please describe
      placeholder: |-
        1. A clear and concise description of what the problem is. Ex. I'm always frustrated when
    validations:
      required: true
  - type: textarea
    id: Solution
    attributes:
      label: Solution Proposed
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case and benefits
      description: Who would benefit from this feature and how?
      placeholder: This would help security teams by...
    validations:
      required: true
  - type: textarea
    id: Alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: Context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
