# Generated by Django 5.1.1 on 2024-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rbac_missing_admin_roles"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="provider",
            name="unique_provider_uids",
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "provider", "uid", "is_deleted"),
                name="unique_provider_uids",
            ),
        ),
    ]
