# Generated by Django 5.1.5 on 2025-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_findings_first_seen"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["tenant_id", "provider_id", "state", "inserted_at"],
                name="scans_prov_state_insert_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scansummary",
            index=models.Index(
                fields=["tenant_id", "scan_id"], name="scan_summaries_tenant_scan_idx"
            ),
        ),
    ]
