# Generated by Django 5.1.5 on 2025-02-07 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_daily_scheduled_tasks_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="uid",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Unique identifier for the provider, set by the provider",
            ),
        ),
    ]
