# Generated by Django 5.1.5 on 2025-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_daily_scheduled_tasks_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="output_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="upload_to_s3",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
