# Generated by Django 5.1.5 on 2025-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_increase_provider_uid_maximum_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="output_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
