# Generated by Django 5.1.5 on 2025-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_scan_report_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="uid",
            field=models.TextField(blank=False, null=False),
        ),
    ]
