# Generated by Django 5.1.7 on 2025-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_integrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="compliance",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="partition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
