# Generated by Django 5.1.5 on 2025-03-25 11:29

from django.db import migrations, models

import api.db_utils


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_integrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="finding",
            name="status",
            field=api.db_utils.StatusEnumField(
                choices=[("FAIL", "Fail"), ("PASS", "Pass"), ("MANUAL", "Manual")]
            ),
        ),
    ]
