# Generated by Django 5.1.5 on 2025-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_finding_muted"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="compliance",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="metadata",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="partition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
