# Generated by Django 5.1.7 on 2025-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_finding_compliance_resource_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="uid",
            field=models.CharField(max_length=600),
        ),
    ]
