# Generated by Django 5.1.7 on 2025-04-29 14:36

import django.db.models.deletion
import uuid6
from django.db import migrations, models

from api.rls import RowLevelSecurityConstraint


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_finding_compliance_resource_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(default=uuid6.uuid7)),
                ("dimension", models.CharField(max_length=32)),
                ("value", models.TextField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "filter_values",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "scan_id"], name="filter_values_scan_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "scan_id", "dimension"],
                        name="filter_values_dim_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "scan_id", "dimension", "value")},
            },
        ),
        migrations.AddConstraint(
            model_name="filtervalue",
            constraint=RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_filtervalue",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
