# Generated by Django 5.1.7 on 2025-04-30 13:04

import uuid

import django.db.models.deletion
import uuid6
from django.db import migrations, models

import api.rls


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_m365_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(default=uuid6.uuid7)),
                ("resource_id", models.UUIDField(default=uuid.uuid4)),
                ("dimension", models.CharField(max_length=32)),
                ("value", models.TextField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "filter_values",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "scan_id", "resource_id", "dimension"],
                        name="filter_val_scan_res_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "scan_id", "dimension", "value"],
                        name="filter_values_dim_idx",
                    ),
                ],
                "unique_together": {
                    ("tenant_id", "scan_id", "resource_id", "dimension", "value")
                },
            },
        ),
        migrations.AddConstraint(
            model_name="filtervalue",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_filtervalue",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
