# Generated by Django 5.1.8 on 2025-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_scan_summaries_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["tenant_id", "id"], name="resources_tenant_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["tenant_id", "provider_id"],
                name="resources_tenant_provider_idx",
            ),
        ),
    ]
