# Generated by Django 5.1.10 on 2025-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_samlconfigurations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="configuration",
            field=models.JSONField(
                default=dict,
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "tenant"),
                name="unique_configuration_per_tenant",
            ),
        ),
    ]
