# Generated by Django 5.1.10 on 2025-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_integration_configuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lighthouseconfiguration",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-2024-11-20", "GPT-4o v2024-11-20"),
                    ("gpt-4o-2024-08-06", "GPT-4o v2024-08-06"),
                    ("gpt-4o-2024-05-13", "GPT-4o v2024-05-13"),
                    ("gpt-4o", "GPT-4o Default"),
                    ("gpt-4o-mini-2024-07-18", "GPT-4o Mini v2024-07-18"),
                    ("gpt-4o-mini", "GPT-4o Mini Default"),
                ],
                default="gpt-4o-2024-08-06",
                help_text="Must be one of the supported model names",
                max_length=50,
            ),
        ),
    ]
