# Generated by Django 5.1.10 on 2025-07-19

from django.db import migrations

from api.rls import APIKeyRowLevelSecurityConstraint


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_add_api_key_model"),
    ]

    operations = [
        # Remove the old restrictive RLS constraint
        migrations.RemoveConstraint(
            model_name="apikey",
            name="rls_on_apikey",
        ),
        # Add the new permissive API key RLS constraint
        migrations.AddConstraint(
            model_name="apikey",
            constraint=APIKeyRowLevelSecurityConstraint(
                field="tenant_id",
                name="rls_on_apikey",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ] 