# Generated by Django 5.1.10 on 2025-07-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_integration_unique_configuration_per_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="output_location",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
