# Generated by Django 5.1.10 on 2025-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_scan_scans_prov_ins_desc_idx"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "tenant"),
                name="unique_configuration_per_tenant",
            ),
        ),
    ]
