# Generated by Django 5.1.10 on 2025-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_alter_scan_output_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lighthouseconfiguration",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-2024-11-20", "GPT-4o v2024-11-20"),
                    ("gpt-4o-2024-08-06", "GPT-4o v2024-08-06"),
                    ("gpt-4o-2024-05-13", "GPT-4o v2024-05-13"),
                    ("gpt-4o", "GPT-4o Default"),
                    ("gpt-4o-mini-2024-07-18", "GPT-4o Mini v2024-07-18"),
                    ("gpt-4o-mini", "GPT-4o Mini Default"),
                    ("gpt-5-2025-08-07", "GPT-5 v2025-08-07"),
                    ("gpt-5", "GPT-5 Default"),
                    ("gpt-5-mini-2025-08-07", "GPT-5 Mini v2025-08-07"),
                    ("gpt-5-mini", "GPT-5 Mini Default"),
                ],
                default="gpt-4o-2024-08-06",
                help_text="Must be one of the supported model names",
                max_length=50,
            ),
        ),
    ]
