# Generated by Django 5.1.10 on 2025-08-20 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0045_alter_scan_output_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integration",
            name="unique_configuration_per_tenant",
        ),
    ]
