# Generated by Django 5.1.10 on 2025-09-23 10:16

import api.rls
import django.db.models.deletion
import drf_simple_apikey.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_integration_unique_configuration_per_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField(default=drf_simple_apikey.models._expiry_date, help_text='Once API key expires, entities cannot use it anymore.', verbose_name='Expires')),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, entities cannot use it anymore. (This cannot be undone.)')),
                ('created', models.DateTimeField(auto_now=True)),
                ('whitelisted_ips', models.JSONField(blank=True, help_text='List of allowed IP addresses for this API key.', null=True)),
                ('blacklisted_ips', models.JSONField(blank=True, help_text='List of denied IP addresses for this API key.', null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'db_table': 'api_keys',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name="tenantapikey",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_tenantapikey",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
