# Generated by Django 5.1.10 on 2025-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_remove_integration_unique_configuration_per_tenant"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scansummary",
            index=models.Index(
                fields=["tenant_id", "scan_id", "severity"],
                include=("fail", "_pass", "muted", "total"),
                name="ss_tenant_scan_sev_status_idx",
            ),
        ),
    ]
