# Generated by Django 5.1.10 on 2025-09-11 13:27

import api.rls
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_integration_unique_configuration_per_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for external API references', unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('role', models.ForeignKey(help_text='Role that defines the permissions for this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
            options={
                'db_table': 'api_keys',
                'abstract': False,
                'indexes': [models.Index(fields=['tenant_id', 'prefix'], name='api_keys_tenant_prefix_idx')],
                'constraints': [api.rls.RowLevelSecurityConstraint('tenant_id', name='rls_on_apikey')],
            },
        ),
    ]
