# Generated by Django 5.1.12 on 2025-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0048_api_key"),
    ]
    operations = [
        migrations.AddField(
            model_name="compliancerequirementoverview",
            name="passed_findings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compliancerequirementoverview",
            name="total_findings",
            field=models.IntegerField(default=0),
        ),
    ]
