# Generated by Django 5.1.13 on 2025-11-06 16:20

import uuid

import django.db.models.deletion

from django.db import migrations, models

import api.rls


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_mute_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartographyScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    api.db_utils.StateEnumField(
                        choices=[
                            ("available", "Available"),
                            ("scheduled", "Scheduled"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "update_tag",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cartography update tag (epoch)",
                        null=True,
                    ),
                ),
                (
                    "neo4j_database",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "ingestion_exceptions",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartography_scans",
                        related_query_name="cartography_scan",
                        to="api.provider",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cartography_scans",
                        related_query_name="cartography_scan",
                        to="api.scan",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cartography_scans",
                        related_query_name="cartography_scan",
                        to="api.task",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "cartography_scans",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "provider_id", "state", "inserted_at"],
                        name="c_scans_prov_state_ins_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "scan_id", "inserted_at"],
                        name="c_scans_scan_ins_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cartographyscan",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_cartographyscan",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
