# Generated by Django 5.1.12 on 2025-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_mute_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lighthouseproviderconfiguration",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("bedrock", "AWS Bedrock"),
                    ("openai_compatible", "OpenAI Compatible"),
                ],
                help_text="LLM provider name",
                max_length=50,
            ),
        )
    ]
