# Generated by Django 5.1.13 on 2025-11-03 00:00

from django.db import migrations

import api.db_utils


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_lighthouse_bedrock_openai_compatible"),
    ]

    operations = [
        # Add the new enum value
        migrations.RunSQL(
            "ALTER TYPE provider ADD VALUE IF NOT EXISTS 'oraclecloud';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update existing records from 'oci' to 'oraclecloud' (if table exists)
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables
                          WHERE table_schema = 'public'
                          AND table_name = 'api_provider') THEN
                    UPDATE api_provider SET provider = 'oraclecloud' WHERE provider = 'oci';
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables
                          WHERE table_schema = 'public'
                          AND table_name = 'api_provider') THEN
                    UPDATE api_provider SET provider = 'oci' WHERE provider = 'oraclecloud';
                END IF;
            END $$;
            """,
        ),
        # Update the field definition with the new choices
        migrations.AlterField(
            model_name="provider",
            name="provider",
            field=api.db_utils.ProviderEnumField(
                choices=[
                    ("aws", "AWS"),
                    ("azure", "Azure"),
                    ("gcp", "GCP"),
                    ("kubernetes", "Kubernetes"),
                    ("m365", "M365"),
                    ("github", "GitHub"),
                    ("oraclecloud", "Oracle Cloud Infrastructure"),
                ],
                default="aws",
            ),
        ),
        # Note: We cannot remove the old 'oci' value from the enum as PostgreSQL
        # does not support removing enum values. The old value will remain in the
        # enum type but will not be used.
    ]
