# Generated by Django 5.1.13 on 2025-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0055_mongodbatlas_provider"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="provider",
            name="unique_provider_uids",
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("tenant_id", "provider", "uid"),
                name="unique_provider_uids",
            ),
        ),
    ]
