# Generated by Django 5.1.14 on 2025-11-26 09:23

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0059_compliance_overview_summary"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="scansummary",
            index=models.Index(
                fields=["tenant_id", "inserted_at"],
                include=["severity", "fail", "muted"],
                name="ss_tenant_time_covering_idx",
            ),
        ),
    ]
