# Generated by Django 5.1.14 on 2025-12-01 13:40

import uuid

import django.db.models.deletion
from django.db import migrations, models

import api.db_utils
import api.rls


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_attack_surface_overview"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyFindingsSeverity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Snapshot date (from scan.completed_at)"
                    ),
                ),
                (
                    "provider_type",
                    api.db_utils.ProviderEnumField(
                        choices=[
                            ("aws", "AWS"),
                            ("azure", "Azure"),
                            ("gcp", "GCP"),
                            ("kubernetes", "Kubernetes"),
                            ("m365", "M365"),
                            ("github", "GitHub"),
                            ("mongodbatlas", "MongoDB Atlas"),
                            ("iac", "IaC"),
                            ("oraclecloud", "Oracle Cloud Infrastructure"),
                        ],
                        help_text="Denormalized from provider.provider for query performance",
                    ),
                ),
                ("critical", models.IntegerField(default=0)),
                ("high", models.IntegerField(default=0)),
                ("medium", models.IntegerField(default=0)),
                ("low", models.IntegerField(default=0)),
                ("informational", models.IntegerField(default=0)),
                ("muted", models.IntegerField(default=0)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_findings_severity",
                        related_query_name="daily_finding_severity",
                        to="api.provider",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_findings_severity",
                        related_query_name="daily_finding_severity",
                        to="api.scan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "daily_findings_severity",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "date"], name="dfs_tenant_date_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "provider_id", "date"],
                        name="dfs_tenant_provider_date_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "provider_type", "date"],
                        name="dfs_tenant_type_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "provider", "date"),
                        name="unique_daily_findings_severity",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyfindingsseverity",
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_dailyfindingsseverity",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
