# Generated by Django migration for scan imported trigger support
"""
Migration: 0066_scan_imported_trigger

Adds the 'imported' trigger type to the Scan model.

This migration extends the scan_trigger PostgreSQL enum to support scans
created from imported external data (e.g., Prowler CLI output files).
Previously, scans could only be 'scheduled' or 'manual'.

Operations:
    1. AlterField: Updates the Django model field to include the new choice.
    2. RunSQL: Adds 'imported' value to the PostgreSQL enum type directly,
       using IF NOT EXISTS for idempotency.

Note:
    The reverse_sql is a no-op because PostgreSQL does not support removing
    enum values. This is a forward-only migration for the enum type.
"""

from django.db import migrations

import api.db_utils


class Migration(migrations.Migration):
    """
    Adds 'imported' as a valid trigger type for scans.

    This enables tracking scans that were created by importing external
    scan results rather than being executed directly by the platform.
    """

    dependencies = [
        ("api", "0065_alibabacloud_provider"),
    ]

    operations = [
        # Update Django model field to recognize the new trigger choice
        migrations.AlterField(
            model_name="scan",
            name="trigger",
            field=api.db_utils.ScanTriggerEnumField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("manual", "Manual"),
                    ("imported", "Imported"),
                ],
            ),
        ),
        # Add the new value to the PostgreSQL enum type
        # Note: IF NOT EXISTS ensures idempotency; reverse is noop since
        # PostgreSQL doesn't support dropping enum values
        migrations.RunSQL(
            "ALTER TYPE scan_trigger ADD VALUE IF NOT EXISTS 'imported';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
