# Generated by Django 5.1.15 on 2026-02-16 09:24

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0076_openstack_provider"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="attackpathsscan",
            name="aps_active_graph_idx",
        ),
        RemoveIndexConcurrently(
            model_name="attackpathsscan",
            name="aps_completed_graph_idx",
        ),
    ]
