# Generated by Django 5.1.15 on 2026-02-16 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0077_remove_attackpathsscan_graph_database_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attackpathsscan",
            name="graph_database",
        ),
        migrations.RemoveField(
            model_name="attackpathsscan",
            name="is_graph_database_deleted",
        ),
    ]
