# Generated by Django 5.1.15 on 2026-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0078_remove_attackpathsscan_graph_database_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="attackpathsscan",
            name="graph_data_ready",
            field=models.BooleanField(default=False),
        ),
    ]
