# Generated by Django 5.1.15 on 2026-02-26 22:11

import django.contrib.postgres.indexes
from django.db import migrations

import api.db_utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_image_provider"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TYPE provider ADD VALUE IF NOT EXISTS 'vercel';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="provider",
            name="provider",
            field=api.db_utils.ProviderEnumField(
                choices=[
                    ("aws", "AWS"),
                    ("azure", "Azure"),
                    ("gcp", "GCP"),
                    ("kubernetes", "Kubernetes"),
                    ("m365", "M365"),
                    ("github", "GitHub"),
                    ("mongodbatlas", "MongoDB Atlas"),
                    ("iac", "IaC"),
                    ("oraclecloud", "Oracle Cloud Infrastructure"),
                    ("alibabacloud", "Alibaba Cloud"),
                    ("cloudflare", "Cloudflare"),
                    ("openstack", "OpenStack"),
                    ("vercel", "Vercel"),
                    ("image", "Image"),
                ],
                default="aws",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text_search"], name="gin_resources_search_idx"
            ),
        ),
    ]
