# Generated by Django 5.1.15 on 2026-03-18

from django.contrib.postgres.indexes import GinIndex, OpClass
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db.models.functions import Upper


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0084_googleworkspace_provider"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="findinggroupdailysummary",
            index=GinIndex(
                OpClass(Upper("check_id"), name="gin_trgm_ops"),
                name="fgds_check_id_trgm_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="findinggroupdailysummary",
            index=GinIndex(
                OpClass(Upper("check_title"), name="gin_trgm_ops"),
                name="fgds_check_title_trgm_idx",
            ),
        ),
    ]
