from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0087_vercel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="manual_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="pass_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="fail_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="manual_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_fail_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_fail_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_pass_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_pass_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_manual_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="new_manual_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_fail_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_fail_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_pass_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_pass_muted_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_manual_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="findinggroupdailysummary",
            name="changed_manual_muted_count",
            field=models.IntegerField(default=0),
        ),
    ]
