# Generated by Django 5.1.15 on 2026-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0093_okta_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="recovery_count",
            field=models.IntegerField(default=0),
        ),
    ]
