import uuid

import api.rls
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0097_attack_paths_scan_db_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantOnboardingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_cloud_accounts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2-10", "2-10"),
                            ("11-50", "11-50"),
                            ("51-200", "51-200"),
                            ("200+", "200+"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "declared_team_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2-5", "2-5"),
                            ("6-20", "6-20"),
                            ("21+", "21+"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "declared_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("security", "Security"),
                            ("devops_platform", "DevOps / Platform"),
                            ("developer", "Developer"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("skipped", models.BooleanField(default=False)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_onboarding_profiles",
                        related_query_name="tenant_onboarding_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "tenant_onboarding_profiles",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="tenantonboardingprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant_id",), name="unique_tenant_onboarding_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantonboardingprofile",
            # `statements` written out explicitly: RowLevelSecurityConstraint
            # .deconstruct() does not serialize it, so an autogenerated
            # migration falls back to ["SELECT"] and leaves the table without
            # INSERT/UPDATE/DELETE policies.
            constraint=api.rls.RowLevelSecurityConstraint(
                "tenant_id",
                name="rls_on_tenantonboardingprofile",
                statements=["SELECT", "INSERT", "UPDATE", "DELETE"],
            ),
        ),
    ]
