name: 'Setup Python with Poetry'
description: 'Setup Python environment with Poetry and install dependencies'
author: 'Prowler'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  working-directory:
    description: 'Working directory for Poetry'
    required: false
    default: '.'
  poetry-version:
    description: 'Poetry version to install'
    required: false
    default: '2.1.1'
  install-dependencies:
    description: 'Install Python dependencies with Poetry'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Replace @master with current branch in pyproject.toml
      if: github.event_name == 'pull_request' && github.base_ref == 'master'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
        echo "Using branch: $BRANCH_NAME"
        sed -i "s|@master|@$BRANCH_NAME|g" pyproject.toml

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pipx install poetry==${{ inputs.poetry-version }}

    - name: Update SDK resolved_reference to latest commit
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        LATEST_COMMIT=$(curl -s "https://api.github.com/repos/prowler-cloud/prowler/commits/master" | jq -r '.sha')
        echo "Latest commit hash: $LATEST_COMMIT"
        sed -i '/url = "https:\/\/github\.com\/prowler-cloud\/prowler\.git"/,/resolved_reference = / {
          s/resolved_reference = "[a-f0-9]\{40\}"/resolved_reference = "'"$LATEST_COMMIT"'"/
        }' poetry.lock
        echo "Updated resolved_reference:"
        grep -A2 -B2 "resolved_reference" poetry.lock

    - name: Update poetry.lock
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: poetry lock

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
        cache-dependency-path: ${{ inputs.working-directory }}/poetry.lock

    - name: Install Python dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry install --no-root
        poetry run pip list
