#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

GROUP_ID[11]='custom'
GROUP_NUMBER[11]='11.0'
GROUP_TITLE[11]='Custom Checks - [custom] ****************************'
GROUP_RUN_BY_DEFAULT[11]='Y' # run it when execute_all is called
GROUP_CHECKS[11]='check1101'
