#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

GROUP_ID[27]='delta-courtesy'
GROUP_NUMBER[27]='27.0'
GROUP_TITLE[27]='(DP) Internet Exposed + IAM - [delta-courtesy] ****************************'

GROUP_RUN_BY_DEFAULT[27]='N' # run it when execute_all is called
GROUP_CHECKS[27]='check11,check12, check13, check14, check15, check16, check17, check18, check19, check110, check111, check112, check113, check114, check115, check116, check117, check118, check119, check120, check121, check122, check41, check42, check45, check46, extra72, extra73, extra74, extra76, extra77, extra78, extra79, extra710, extra711, extra716, extra723, extra727, extra731, extra736, extra738, extra745, extra748, extra749, extra750, extra751, extra752, extra753, extra754, extra755, extra770, extra771, extra778, extra779, extra787, extra788, extra795, extra796, extra798, extra7102, extra7134, extra7135, extra7136, extra7137, extra7138'
