apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prowler-read-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prowler-read-cluster
subjects:
- kind: ServiceAccount
  name: prowler-sa
  namespace: prowler-ns
