{{- if .Values.valkey.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler.fullname" . }}-api-valkey
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  VALKEY_SCHEME: {{ .Values.valkey.scheme | default "redis" | quote }}
  VALKEY_USERNAME: {{ .Values.valkey.username | default "" | quote }}
  VALKEY_PASSWORD: {{ .Values.valkey.password | default "" | quote }}
  VALKEY_HOST: "{{ include "prowler.fullname" . }}-valkey"
  VALKEY_PORT: "6379"
  VALKEY_DB: "0"
{{- end -}}
