# Generated by Django 5.0.6 on 2024-06-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_brand', models.CharField(max_length=255)),
                ('card_exp_month', models.IntegerField()),
                ('card_exp_year', models.IntegerField()),
                ('card_last4', models.CharField(max_length=4)),
                ('onboarding_required', models.BooleanField()),
                ('onboarding_step', models.CharField(max_length=255)),
                ('onboarding_completed_at', models.DateTimeField()),
                ('aws_account_id', models.CharField(max_length=255)),
                ('off_boarded', models.BooleanField()),
                ('billing_type', models.CharField(max_length=255)),
                ('billing_cancel_at', models.DateTimeField()),
                ('billing_current_period_end_at', models.DateTimeField()),
                ('billing_free_resource_count', models.IntegerField()),
                ('grafana_org_name', models.CharField(max_length=255)),
                ('billing_email', models.CharField(max_length=255)),
                ('scan_window_start_at', models.DateTimeField()),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('enable', models.BooleanField()),
                ('provider_id', models.CharField(max_length=255)),
                ('provider_data', models.JSONField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected', models.BooleanField()),
                ('last_checked_at', models.DateTimeField()),
                ('alias', models.CharField(max_length=255)),
                ('scanner_configuration', models.JSONField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
            options={
                'db_table': 'cloud_accounts',
            },
        ),
    ]
