# Generated by Django 5.0.6 on 2024-06-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cloudaccount_groups_cloudaccount_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='aws_account_id',
            field=models.OneToOneField(db_column='aws_account_id', on_delete=django.db.models.deletion.CASCADE, to='api.cloudaccount', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='account_id',
            field=models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
