# Generated by Django 5.0.6 on 2024-06-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audit_aws_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='billing_cancel_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_current_period_end_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_free_resource_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_exp_month',
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_exp_year',
        ),
        migrations.RemoveField(
            model_name='account',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='grafana_org_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='off_boarded',
        ),
        migrations.RemoveField(
            model_name='account',
            name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='onboarding_required',
        ),
        migrations.RemoveField(
            model_name='account',
            name='onboarding_step',
        ),
        migrations.RemoveField(
            model_name='account',
            name='token',
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='last_checked_at',
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='provider_data',
        ),
        migrations.RemoveField(
            model_name='cloudaccount',
            name='scanner_configuration',
        ),
    ]
