# Generated by Django 4.2.13 on 2024-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_account_billing_cancel_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
