#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# AWS-CLI detector variable
aws_cli_detector() {
  if [ ! -z $(which aws) ]; then
    AWSCLI=$(which aws)
  elif [ ! -z $(type -p aws) ]; then
    AWSCLI=$(type -p aws)
  else
    echo -e "\n$RED ERROR!$NORMAL AWS-CLI (aws command) not found. Make sure it is installed correctly and in your \$PATH\n"
    EXITCODE=1
    exit $EXITCODE
  fi
}

set_aws_default_output() {
  # Ensures command output will always be set to JSON.
  # If the default value is already set, ORIGINAL_OUTPUT will be used to store it and reset it at cleanup
  if [[ -z "${AWS_DEFAULT_OUTPUT}" ]]; then
    ORIGINAL_OUTPUT=$AWS_DEFAULT_OUTPUT
    export AWS_DEFAULT_OUTPUT="json"
  else
    export AWS_DEFAULT_OUTPUT="json"
  fi
}
