#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

prowlerBanner() {
  if [[ $BANNER != "0" ]]; then
    echo -e "$CYAN                          _"
    echo -e "  _ __  _ __ _____      _| | ___ _ __"
    echo -e " | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|"
    echo -e " | |_) | | | (_) \ V  V /| |  __/ |"
    echo -e " | .__/|_|  \___/ \_/\_/ |_|\___|_|v$PROWLER_VERSION"
    echo -e " |_|$NORMAL$BLUE the handy cloud security tool$NORMAL\n"
    echo -e "$YELLOW Date: $(date)"
    printColorsCode
  fi
}

infoReferenceLong(){
  # Report review note:
  echo -e ""
  echo -e "For more information on the Prowler, feedback and issue reporting:"
  echo -e "https://github.com/toniblyx/prowler"
  echo -e ""
  echo -e "For more information on the CIS benchmark:"
  echo -e "https://benchmarks.cisecurity.org/tools2/amazon/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.1.0.pdf"
}
