#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Colors
# NOTE: Your editor may NOT show the 0x1b / escape character left of the '['
set_colors() {
  if [[ "${MODE}" =~ "mono" ]]
  then
    NORMAL=""
    WARNING=""
    NOTICE=""
    OK=""
    BAD=""
    CYAN=""
    BLUE=""
    BROWN=""
    MAGENTA=""
    RED=""
    YELLOW=""
  else
    NORMAL="[0;39m"
    WARNING="[0;33m"          # Warning (brown)
    NOTICE="[1;33m"           # Notice (yellow)
    OK="[1;32m"               # Ok (green)
    BAD="[1;31m"              # Bad (red)
    CYAN="[0;36m"
    BLUE="[0;34m"
    BROWN="[0;33m"
    MAGENTA="[1;35m"
    RED="[1;31m"
    YELLOW="[1;33m"
  fi
}

printColorsCode(){
  if [[ ! "$MODE" =~ "mono" ]]
  then
    echo -e "\n$NORMAL Color code for results: "
    echo -e " - $NOTICE INFO (Information)$NORMAL"
    echo -e " - $OK PASS (Recommended value)$NORMAL"
    echo -e " - $WARNING WARNING (Ignored by allowlist)$NORMAL"
    echo -e " - $BAD FAIL (Fix required)$NORMAL"
  fi
}
