#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Output Colors
OPTRED="[1;31m"
OPTNORMAL="[0;39m"
MONOCHROME=0

# AWS Region
REGION=""
FILTERREGION=""

# Max AWS CLI items
MAXITEMS=100

# Default output mode
MODE="text"

# Security Hub
SEND_TO_SECURITY_HUB=0

# Date & Time
PROWLER_START_TIME=$( date -u +"%Y-%m-%dT%H:%M:%S%z" )
OUTPUT_DATE=$(date -u +"%Y%m%d%H%M%S")

# Default Prowler Options
QUIET=0
SEP=','
KEEPCREDREPORT=0
EXITCODE=0
FAILED_CHECK_FAILED_SCAN=1
