#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Output Colors
OPTRED="[1;31m"
export OPTRED
OPTNORMAL="[0;39m"
export OPTNORMAL

# AWS Region
REGION=""
export REGION
FILTERREGION=""
export FILTERREGION

# Max AWS CLI items
MAXITEMS=100
export MAXITEMS

# Default output mode
MODE="text"
export MODE

# Security Hub
SEND_TO_SECURITY_HUB=0
export SEND_TO_SECURITY_HUB

# Date & Time
TZ=UTC
export TZ
PROWLER_START_TIME=$( date -u +"%Y-%m-%dT%H:%M:%S%z" )
export PROWLER_START_TIME
OUTPUT_DATE=$(date -u +"%Y%m%d%H%M%S")
export OUTPUT_DATE

# Default Prowler Options
QUIET=0
export QUIET
SEP=','
export SEP
KEEPCREDREPORT=0
export KEEPCREDREPORT
EXITCODE=0
export EXITCODE
FAILED_CHECK_FAILED_SCAN=1
export FAILED_CHECK_FAILED_SCAN
