#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2021) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

copyToS3() {
  # Prowler will copy each format to its own folder in S3, that is for better handling
  # and processing by Quicksight or others.
  # Also, check if -F was introduced
  if [ -n "${OUTPUT_FILE_NAME+x}" ]; then
    OUTPUT_PATH="${OUTPUT_FILE_NAME}"
  else
    OUTPUT_PATH="$OUTPUT_DIR/prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}"
  fi

  OIFS="${IFS}"
  IFS=','
  for MODE_TYPE in ${MODE}
  do
    IFS="${OIFS}"
    case ${MODE_TYPE} in
      csv)
        s3cp "${OUTPUT_PATH}" "${EXTENSION_CSV}"
      ;;
      html)
        s3cp "${OUTPUT_PATH}" "${EXTENSION_HTML}"
      ;;
      json)
        s3cp "${OUTPUT_PATH}" "${EXTENSION_JSON}"
      ;;
      json-asff)
        s3cp "${OUTPUT_PATH}" "${EXTENSION_ASFF}"
      ;;
      *)
        echo "$OPTRED ERROR!$OPTNORMAL - Invalid output format copying to S3. Use -h for help."
        exit 1
      ;;
    esac
  done
}

s3cp(){
  OUTPUT_PATH="${1}"
  EXTENSION="${2}"
  "${AWSCLI}" ${PROFILE_OPT} s3 cp "${OUTPUT_PATH}.${EXTENSION}" s3://"${OUTPUT_BUCKET}"/${EXTENSION}/ --acl bucket-owner-full-control
}
