#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check115="1.15"
CHECK_TITLE_check115="[check115] Ensure security questions are registered in the AWS account (Not Scored)"
CHECK_SCORED_check115="SCORED"
CHECK_TYPE_check115="LEVEL1"
CHECK_ALTERNATE_check115="check115"

check115(){
  # "Ensure security questions are registered in the AWS account (Not Scored)"
  textInfo "No command available for check 1.15 "
  textInfo "Login to the AWS Console as root & click on the Account "
  textInfo "Name -> My Account -> Configure Security Challenge Questions "
}
