#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2019) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra747="7.47"
CHECK_TITLE_extra747="[extra747] Check if API Gateway has CloudWatch Logs enabled (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_extra747="NOT_SCORED"
CHECK_TYPE_extra747="EXTRA"
CHECK_ALTERNATE_check747="extra747"

extra747(){
  for regx in $REGIONS; do
    LIST_OF_REST_APIS=$($AWSCLI $PROFILE_OPT --region $regx apigateway get-rest-apis --query 'items[*].id' --output text)
    if [[ $LIST_OF_REST_APIS ]];then
      for api in $LIST_OF_REST_APIS; do
        LIST_OF_STAGES=$($AWSCLI $PROFILE_OPT --region $regx apigateway get-stages --rest-api-id $api --query 'item[*].stageName' --output text)
        if [[ $LIST_OF_STAGES ]]; then 
          for stage in $LIST_OF_STAGES; do
            CHECK_CLOUDWATCHLOG=$($AWSCLI $PROFILE_OPT --region $regx apigateway get-stages --rest-api-id $api --query "item[?stageName==\`$stage\`].methodSettings" --output text|awk '{ print $6 }'|egrep 'ERROR|INFO')
            if [[ $CHECK_CLOUDWATCHLOG ]]; then
                textPass "$regx: API Gateway ID $api in $stage has CloudWatch Logs configured" "$regx"
              else 
                textFail "$regx: API Gateway ID $api in $stage has not CloudWatch Logs configured" "$regx"
            fi 
          done 
        fi
      done
    else
      textInfo "$regx: No API Gateways found" "$regx"
    fi
  done
}
