#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra711="7.11"
CHECK_TITLE_extra711="[extra711] Check for Publicly Accessible Redshift Clusters (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_extra711="NOT_SCORED"
CHECK_TYPE_extra711="EXTRA"
CHECK_ALTERNATE_check711="extra711"

extra711(){
  # "Check for Publicly Accessible Redshift Clusters (Not Scored) (Not part of CIS benchmark)"
  textInfo "Looking for Reshift clusters in all regions...  "
  for regx in $REGIONS; do
    LIST_OF_PUBLIC_REDSHIFT_CLUSTERS=$($AWSCLI redshift describe-clusters $PROFILE_OPT --region $regx --query 'Clusters[?PubliclyAccessible == `true`].[ClusterIdentifier,Endpoint.Address]' --output text)
    if [[ $LIST_OF_PUBLIC_REDSHIFT_CLUSTERS ]];then
      while read -r cluster;do
        CLUSTER_ID=$(echo $cluster | awk '{ print $1; }')
        CLUSTER_ENDPOINT=$(echo $cluster | awk '{ print $2; }')
        textFail "$regx: Cluster: $CLUSTER_ID at Endpoint: $CLUSTER_ENDPOINT is publicly accessible!" "$regx"
      done <<< "$LIST_OF_PUBLIC_REDSHIFT_CLUSTERS"
      else
        textPass "$regx: no Publicly Accessible Redshift Clusters found" "$regx"
    fi
  done
}
