#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check121="1.21"
CHECK_TITLE_check121="[check121] Ensure IAM instance roles are used for AWS resource access from instances (Not Scored)"
CHECK_SCORED_check121="NOT_SCORED"
CHECK_TYPE_check121="LEVEL2"
CHECK_ALTERNATE_check121="check121"

check121(){
  # "Ensure IAM instance roles are used for AWS resource access from instances (Not Scored)"
  textInfo "No command available for check 1.21 "
  textInfo "See section 1.21 on the CIS Benchmark guide for details "
}
