#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2019) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra796="7.96"
CHECK_TITLE_extra796="[extra796] Restrict Access to the EKS Control Plane Endpoint"
CHECK_SCORED_extra796="NOT_SCORED"
CHECK_TYPE_extra796="EXTRA"
CHECK_SEVERITY_extra796="High"
CHECK_ASFF_RESOURCE_TYPE_extra796="AwsEksCluster"
CHECK_ALTERNATE_check796="extra796"

extra796(){
  textInfo "Looking for public access CIDRs for EKS clusters across all regions... "
  for regx in $REGIONS; do
    # Get a list of EKS clusters (Unless us-west-1 which doesn't support EKS):
    if [[ $regx == "us-west-1" ]]; then
      textInfo "$regx: EKS not supported in this region" "$regx"
    else
      CLUSTERS=$($AWSCLI eks list-clusters $PROFILE_OPT --region $regx --query 'clusters[]' --output text)
    fi
    if [[ $CLUSTERS ]]; then
      for CLUSTER in $CLUSTERS;do
        CLUSTERDEF=$($AWSCLI eks describe-cluster $PROFILE_OPT --region $regx --name $CLUSTER --query 'cluster.resourcesVpcConfig')
        PUB_ENABLED=$(echo $CLUSTERDEF | jq -r '.endpointPublicAccess')
        PRIV_ENABLED=$(echo $CLUSTERDEF | jq -r '.endpointPrivateAccess')
        PUB_ACCESS_CIDRS=$(echo $CLUSTERDEF | jq -r '.publicAccessCidrs')

        if [[ $PUB_ENABLED == "false" ]] && [[ $PRIV_ENABLED == "true" ]] ; then
          textPass "$regx: Cluster endpoint access is private for EKS cluster $CLUSTER" "$regx"
        else
          if [[ $(echo $PUB_ACCESS_CIDRS | grep "0.0.0.0/0") ]] ; then
            textFail "$regx: Cluster control plane access is not restricted for EKS cluster $CLUSTER" "$regx"
          else
            textPass "$regx: Cluster control plane access is restricted for EKS cluster $CLUSTER" "$regx"
          fi
        fi
      done
    else
      if [[ $regx != "us-west-1" ]]; then
        textInfo "$regx: No EKS clusters found" "$regx"
      fi
    fi
  done
}
