#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Remediation:
#
# https://www.cloudconformity.com/knowledge-base/aws/RDS/instance-deletion-protection.html
# https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html
#
# aws rds modify-db-instance \
#	--region us-east-1 \
#	--db-instance-identifier test-db \
#	--deletion-protection \
#	[--apply-immediately | --no-apply-immediately]

CHECK_ID_extra7119="7.119"
CHECK_TITLE_extra7119="[extra7119] Check if Security configurations used by ETL Development endpoints have S3 encryption enabled."
CHECK_SCORED_extra7119="NOT_SCORED"
CHECK_TYPE_extra7119="EXTRA"
CHECK_SEVERITY_extra7119="Medium"
CHECK_ASFF_RESOURCE_TYPE_extra7119="AwsGlue"
CHECK_ALTERNATE_check7119="extra7119"

extra7119(){
  textInfo "Looking for Development Endpoints in all regions...  "
  for regx in $REGIONS; do
    LIST_EP_SC=$($AWSCLI glue get-dev-endpoints $PROFILE_OPT --region $regx --query 'DevEndpoints[*].{Name:EndpointName,Security:SecurityConfiguration}' --output json)
    if [[ ! -z "$LIST_EP_SC" ]]; then
      for ep in $(echo "${LIST_EP_SC}"| jq -r '.[] | @base64');do
        ENDPOINT_NAME=$(echo $ep | base64 --decode | jq -r '.Name')
        ENDPOINT_SC=$(echo $ep | base64 --decode | jq -r '.Security // empty')
        if [[ ! -z "$ENDPOINT_SC" ]]; then
          ENDPOINT_SC_ENCRYPTION=$($AWSCLI glue get-security-configuration --name "${ENDPOINT_SC}" $PROFILE_OPT --region $regx --query 'SecurityConfiguration.EncryptionConfiguration.S3Encryption[0].S3EncryptionMode' --output text)
          if [[ "$ENDPOINT_SC_ENCRYPTION" == "DISABLED" ]]; then
            textFail "$regx: Development Endpoint $ENDPOINT_NAME does not have S3 encryption enabled!" "$regx"
          else
            textPass "$regx: Development Endpoint $ENDPOINT_NAME has S3 encryption enabled" "$regx"
          fi
        else
          textInfo "$regx: No Security Configuration found for Development Endpoint $ENDPOINT_NAME" "$regx"
        fi
      done
    else
      textInfo "$regx: There are no Development Endpoints" "$regx"
    fi
  done
}


