#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra7115="7.115"
CHECK_TITLE_extra7115="[extra7115] Check if Glue database connection has SSL connection enabled."
CHECK_SCORED_extra7115="NOT_SCORED"
CHECK_TYPE_extra7115="EXTRA"
CHECK_SEVERITY_extra7115="Medium"
CHECK_ASFF_RESOURCE_TYPE_extra7115="AwsGlue"
CHECK_ALTERNATE_check7115="extra7115"
CHECK_SERVICENAME_extra7115="glue"
CHECK_RISK_extra7115='Data exfiltration could happen if information is not protected in transit.'
CHECK_REMEDIATION_extra7115='Configure encryption settings for crawlers; ETL jobs; and development endpoints using security configurations in AWS Glue.'
CHECK_DOC_extra7115='https://docs.aws.amazon.com/glue/latest/dg/encryption-in-transit.html'
CHECK_CAF_EPIC_extra7115='Data Protection'

extra7115(){
  for regx in $REGIONS; do
    CONNECTION_LIST=$($AWSCLI glue get-connections $PROFILE_OPT --region $regx  --output json --query 'ConnectionList[*].{Name:Name,SSL:ConnectionProperties.JDBC_ENFORCE_SSL}')
    if [[ $CONNECTION_LIST != '[]' ]]; then
      for connection in $(echo "${CONNECTION_LIST}" | jq -r '.[] | @base64'); do
          CONNECTION_NAME=$(echo $connection | base64 --decode   | jq -r '.Name' )
          CONNECTION_SSL_STATE=$(echo $connection | base64 --decode  | jq -r '.SSL')
          if [[ "$CONNECTION_SSL_STATE" == "false" ]]; then
              textFail "$regx: Glue connection $CONNECTION_NAME has SSL connection disabled"  "$regx"
          else 
              textPass "$regx: Glue connection $CONNECTION_NAME has SSL connection enabled"  "$regx"
          fi
      done
    else 
      textInfo "$regx: There are no Glue connections" "$regx"
    fi 
  done     
}
