#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
CHECK_ID_extra764="7.64"
CHECK_TITLE_extra764="[extra764] Check if S3 buckets have secure transport policy (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_extra764="NOT_SCORED"
CHECK_TYPE_extra764="EXTRA"
CHECK_SEVERITY_extra764="Medium"
CHECK_ASFF_RESOURCE_TYPE_extra764="AwsS3Bucket"
CHECK_ALTERNATE_check764="extra764"
CHECK_ASFF_COMPLIANCE_TYPE_extra764="ens-mp.com.2.aws.s3.1"
CHECK_SERVICENAME_extra764="s3"
CHECK_RISK_extra764='If HTTPS is not enforced on the bucket policy; communication between clients and S3 buckets can use unencrypted HTTP. As a result; sensitive information could be transmitted in clear text over the network or internet.'
CHECK_REMEDIATION_extra764='Ensure that S3 buckets has encryption in transit enabled.'
CHECK_DOC_extra764='https://docs.aws.amazon.com/AmazonS3/latest/dev/security-best-practices.html'
CHECK_CAF_EPIC_extra764='Data Protection'


extra764(){
  LIST_OF_BUCKETS=$($AWSCLI s3api list-buckets $PROFILE_OPT --query Buckets[*].Name --output text --region $REGION|xargs -n1)
  if [[ $LIST_OF_BUCKETS ]]; then
    for bucket in $LIST_OF_BUCKETS;do
      TEMP_STP_POLICY_FILE=$(mktemp -t prowler-${ACCOUNT_NUM}-${bucket}.policy.XXXXXXXXXX)
      BUCKET_LOCATION=$($AWSCLI s3api get-bucket-location $PROFILE_OPT --region $REGION --bucket $bucket --output text 2>&1)
      if [[ $(echo "$BUCKET_LOCATION" | grep AccessDenied) ]]; then
        textFail "Access Denied Trying to Get Bucket Location for $bucket"
        continue
      fi
      if [[ $BUCKET_LOCATION == "None" ]]; then
        BUCKET_LOCATION="us-east-1"
      fi
      if [[ $BUCKET_LOCATION == "EU" ]]; then
        BUCKET_LOCATION="eu-west-1"
      fi
      # get bucket policy
      $AWSCLI s3api get-bucket-policy $PROFILE_OPT --bucket $bucket --output text --query Policy --region $BUCKET_LOCATION > $TEMP_STP_POLICY_FILE 2>&1
      if [[ $(grep AccessDenied $TEMP_STP_POLICY_FILE) ]]; then
        textFail "Access Denied Trying to Get Bucket Policy for $bucket"
        rm -f $TEMP_STP_POLICY_FILE
        continue
      fi
      if [[ $(grep NoSuchBucketPolicy $TEMP_STP_POLICY_FILE) ]]; then
        textFail "No bucket policy for $bucket"
        rm -f $TEMP_STP_POLICY_FILE
        continue
      fi

      # https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/
      # checking if $TEMP_STP_POLICY_FILE is a valid json before converting it to json with jq
      policy_str=$(cat "$TEMP_STP_POLICY_FILE")
      if jq -e . >/dev/null 2>&1 <<< "$policy_str"; then
        CHECK_BUCKET_STP_POLICY_PRESENT=$(cat $TEMP_STP_POLICY_FILE | jq --arg arn "arn:${AWS_PARTITION}:s3:::${bucket}" \
          '.Statement[]|select((((.Principal|type == "object") and .Principal.AWS == "*") or ((.Principal|type == "string") and .Principal == "*")) and .Effect=="Deny" and (.Action=="s3:*" or .Action=="*") and (.Resource|type == "array") and (.Resource|map({(.):0})[]|has($arn)) and (.Resource|map({(.):0})[]|has($arn+"/*")) and .Condition.Bool."aws:SecureTransport" == "false")')
        if [[ $CHECK_BUCKET_STP_POLICY_PRESENT ]]; then
          textPass "Bucket $bucket has S3 bucket policy to deny requests over insecure transport"
        else
          textFail "Bucket $bucket allows requests over insecure transport"
        fi
      else
          textInfo "Unknown Error occurred: $policy_str"
      fi
      rm -fr $TEMP_STP_POLICY_FILE
    done

  else
    textInfo "No S3 Buckets found"
  fi
}
