#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

CHECK_ID_extra729="7.29"
CHECK_TITLE_extra729="[extra729] Ensure there are no EBS Volumes unencrypted (Not Scored) (Not part of CIS benchmark)"
CHECK_SCORED_extra729="NOT_SCORED"
CHECK_TYPE_extra729="EXTRA"
CHECK_ALTERNATE_check729="extra729"

extra729(){
  # "Ensure there are no EBS Volumes unencrypted (Not Scored) (Not part of CIS benchmark)"
  textInfo "Looking for EBS Volumes in all regions...  "
  for regx in $REGIONS; do
    LIST_OF_EBS_NON_ENC_VOLUMES=$($AWSCLI ec2 describe-volumes $PROFILE_OPT --region $regx --query 'Volumes[?Encrypted==`false`].VolumeId' --output text)
    if [[ $LIST_OF_EBS_NON_ENC_VOLUMES ]];then
      for volume in $LIST_OF_EBS_NON_ENC_VOLUMES; do
        textFail "$regx: $volume is not encrypted!" "$regx"
      done
    fi
    LIST_OF_EBS_ENC_VOLUMES=$($AWSCLI ec2 describe-volumes $PROFILE_OPT --region $regx --query 'Volumes[?Encrypted==`true`].VolumeId' --output text)
    if [[ $LIST_OF_EBS_ENC_VOLUMES ]];then
      for volume in $LIST_OF_EBS_ENC_VOLUMES; do
        textPass "$regx: $volume is encrypted" "$regx"
      done
    fi
  done
}
