name: 'CI: Zizmor'

on:
  push:
    branches:
      - 'master'
      - 'v5.*'
    paths:
      - '.github/**'
  pull_request:
    branches:
      - 'master'
      - 'v5.*'
    paths:
      - '.github/**'
  schedule:
    - cron: '30 06 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    if: github.repository == 'prowler-cloud/prowler'
    name: GitHub Actions Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            ghcr.io:443
            pkg-containers.githubusercontent.com:443
            api.github.com:443

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          token: ${{ github.token }}
