name: 'Helm: Chart Release'
# DISCLAIMER: This workflow is not maintained by the Prowler team. Refer to contrib/k8s/helm/prowler-app for the source code.

on:
  release:
    types:
      - 'published'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CHART_PATH: contrib/k8s/helm/prowler-app

permissions: {}

jobs:
  release-helm-chart:
    if: github.repository == 'prowler-cloud/prowler'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Set appVersion from release tag
        run: |
          RELEASE_TAG="${GITHUB_EVENT_RELEASE_TAG_NAME}"
          echo "Setting appVersion to ${RELEASE_TAG}"
          sed -i "s/^appVersion:.*/appVersion: \"${RELEASE_TAG}\"/" ${{ env.CHART_PATH }}/Chart.yaml
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: Update chart dependencies
        run: helm dependency update ${{ env.CHART_PATH }}

      - name: Package Helm chart
        run: helm package ${{ env.CHART_PATH }} --destination .helm-packages

      - name: Push chart to GHCR
        run: |
          PACKAGE=$(ls .helm-packages/*.tgz)
          helm push "$PACKAGE" oci://ghcr.io/${{ github.repository_owner }}/charts
